# Site settings
title: Foxconn Builders Corporation
email: foxconn.builders@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Foxconn Builders, based in the Philippines, exclusively distributes DAYU Floodgate made with the finest and most durable material - the 6063-T5 Aluminum Alloy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://foxconnbuilders.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

sass:
    style: :compressed

# Build settings
markdown: kramdown
